### PR TITLE
Optimization for handleUnionSchema.

### PR DESCRIPTION
**Pull request by prashastia**
Replaces the existing implementation with an if-else based to increase performance. 

@talatuyarer - Please have a look.

/gcbrun

### CODE REVIEW

**Comment by talatuyarer** [comment]
@prashastia The change looks good to me. However I dont have permission to approve your PR.

**Comment by prashastia** [comment]
> @prashastia The change looks good to me. However I dont have permission to approve your PR.

Thanks!, Could you kindly add yourself as a reviewer and then try?

**Comment by jayehwhyehentee** [comment]
@clmccart We need to find a way for GMF folks with GitHub accounts to be able to review or even contribute to this project. Any suggestions?

**Comment by clmccart** [comment]
> @clmccart We need to find a way for GMF folks with GitHub accounts to be able to review or even contribute to this project. Any suggestions?

i think you'll have to reach out to the repo owners and ask them to add us as contributors to the repo

**Review by clmccart — APPROVED** [review]

**Review by jayehwhyehentee — APPROVED** [review]

**Pull request merged**
