### PR TITLE
Fix artifact groupid name

### PR DESCRIPTION
**Pull request by prodriguezdefino**

### CODE REVIEW

**Review by davidrabinowitz — CHANGES_REQUESTED** [review]
Is it possible to update the PR to include just the POM files?

**Comment by prodriguezdefino** [comment]
> Is it possible to update the PR to include just the POM files?

yes, since all the PRs were done cascading one from the previous one, you see here the accumulated differences from main branch. 

here is the actual file diffs of the changes considering only the previous PR #50: 
```
$ git diff test_bqstoragereadapi_error..fix_artifact_groupid_name --name-only
.asf.yaml
cloudbuild/presubmit.sh
flink-connector-bigquery-examples/pom.xml
flink-connector-bigquery-examples/src/main/java/com/google/cloud/flink/bigquery/examples/BigQueryExample.java
flink-connector-bigquery/pom.xml
flink-sql-connector-bigquery/pom.xml
pom.xml
tools/maven/clover.xml
```

The largest remaining changes are on #45 and #46, once those reach main branch the size of accumulated changes on all subsequent PRs will decrease.

**Review by davidrabinowitz — APPROVED** [review]

**Pull request merged**
